services:
  renco.app:
    container_name: renco_apps
    build:
      context: .
      dockerfile: .build/Dockerfile
      args:
        BINARY_NAME: "${APP_NAME:-renco}"
    ports:
      - "${PORT:-3001}:3001"
    command: ["./renco", "http"]
    env_file:
      - .env
    networks:
      - renco-postgresql
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: renco-db-test
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - renco-postgresql
    restart: unless-stopped

networks:
  renco-postgresql:
    driver: bridge
volumes:
  postgres:
    driver: local
